# gh-coda config
# See: https://github.com/lovelesslabs/gh-coda

# Merge settings
auto_merge: true
delete_branch_on_merge: true
allow_squash_merge: true
allow_merge_commit: false
allow_rebase_merge: true

# Features
enable_discussions: true
enable_projects: false
enable_wiki: false

# Security
enable_secret_scanning: true
enable_secret_scanning_push_protection: true
dependabot_alerts: true
dependabot_security_updates: true

# 1Password secrets sync (optional)
secrets_tags: claylo-github-actions
secrets_app: actions

rulesets:
  - name: Protect main branch
    target: branch                    # branch or tag
    enforcement: active               # active, evaluate, or disabled
    conditions:
      ref_name:
        include:
          - "~DEFAULT_BRANCH"         # or: refs/heads/main, refs/heads/release/*
        exclude: []
    rules:
      - type: pull_request
        parameters:
          required_approving_review_count: 0
          dismiss_stale_reviews_on_push: true
          require_code_owner_review: false
      - type: required_status_checks
        parameters:
          strict_required_status_checks_policy: true
          required_status_checks:
            - context: ci/check
      - type: non_fast_forward        # Prevent force pushes
      - type: deletion                # Prevent branch deletion
      - type: required_linear_history
